-- Generated from generator/demo_specs/aws-philippines-banking-bsp-regulatory.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-banking-bsp-regulatory
-- This is the schema that is actually deployed for PH_BANKING_BSP_REGULATORY.

-- Alerts fire on the bottom tail of CAR Ratio
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_CAR_RATIO) AS T
  FROM RAW.FINANCIAL_DATA
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_CAR_RATIO <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_CAR_RATIO), 2) AS AVG_CAR_RATIO,
  ROUND(AVG(f.KPI_STRESS_CAR_SEVERE), 2) AS AVG_STRESS_CAR_SEVERE,
  ROUND(AVG(f.KPI_LCR), 2) AS AVG_LCR
FROM RAW.FINANCIAL_DATA f
JOIN RAW.REPORT_CATALOG e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_CAR_RATIO), 2) AS AVG_CAR_RATIO,
  ROUND(AVG(f.KPI_STRESS_CAR_SEVERE), 2) AS AVG_STRESS_CAR_SEVERE,
  ROUND(AVG(f.KPI_LCR), 2) AS AVG_LCR
FROM RAW.FINANCIAL_DATA f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_CAR_RATIO) AS KPI_CAR_RATIO, AVG(KPI_LCR) AS KPI_LCR, AVG(KPI_STRESS_CAR_SEVERE) AS KPI_STRESS_CAR_SEVERE FROM RAW.FINANCIAL_DATA),
     en AS (SELECT SUM(KPI_BSP_FINDINGS_OPEN) AS KPI_BSP_FINDINGS_OPEN, SUM(KPI_REPORTS_SUBMITTED) AS KPI_REPORTS_SUBMITTED, SUM(KPI_CREDIT_LOSS_SEVERE) AS KPI_CREDIT_LOSS_SEVERE, SUM(KPI_LIQUIDITY_BUFFER) AS KPI_LIQUIDITY_BUFFER FROM RAW.REPORT_CATALOG)
  SELECT 1 AS SORT_ORDER, 'CAR Ratio' AS TITLE, KPI_CAR_RATIO AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CAR_RATIO), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'LCR' AS TITLE, KPI_LCR AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_LCR)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'BSP Findings Open' AS TITLE, KPI_BSP_FINDINGS_OPEN AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_BSP_FINDINGS_OPEN)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Reports Submitted' AS TITLE, KPI_REPORTS_SUBMITTED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_REPORTS_SUBMITTED)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Stress CAR (Severe)' AS TITLE, KPI_STRESS_CAR_SEVERE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_STRESS_CAR_SEVERE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Credit Loss (Severe)' AS TITLE, KPI_CREDIT_LOSS_SEVERE AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_CREDIT_LOSS_SEVERE) / 1000000000)) AS DECIMAL(38,0))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Liquidity Buffer' AS TITLE, KPI_LIQUIDITY_BUFFER AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_LIQUIDITY_BUFFER) / 1000000000)) AS DECIMAL(38,0))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
