-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for BSP Regulatory Reporting & Compliance Automation
-- ============================================================================
USE DATABASE REGULATORY_REPORTING;
USE SCHEMA ML;

-- ML.CLASSIFICATION: REPORT_ERROR_PREDICTOR
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.REPORT_ERROR_PREDICTOR(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.REPORT_READINESS'),
  TARGET_COLNAME => 'WILL_FAIL_VALIDATION'
);

-- ML.ANOMALY_DETECTION: DATA_QUALITY_ANOMALY
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.DATA_QUALITY_ANOMALY(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.RECONCILIATION_STATUS'),
  SERIES_COLNAME => 'SOURCE_SYSTEM',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'GAP_AMOUNT',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.DATA_QUALITY_ANOMALY_RESULTS AS
SELECT * FROM TABLE(ML.DATA_QUALITY_ANOMALY!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.RECONCILIATION_STATUS'), SERIES_COLNAME => 'SOURCE_SYSTEM', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'GAP_AMOUNT'));

