-- ============================================================================
-- 99_RESET.SQL — Reset BSP Regulatory Reporting & Compliance Automation to clean demo state
-- ============================================================================
USE DATABASE REGULATORY_REPORTING;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_EXTRACT_GL SUSPEND;
ALTER TASK IF EXISTS APP.TASK_VALIDATE_DATA SUSPEND;
ALTER TASK IF EXISTS APP.TASK_GENERATE_REPORTS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_RECONCILE SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.REPORT_READINESS REFRESH;
ALTER DYNAMIC TABLE CURATED.RECONCILIATION_STATUS REFRESH;
ALTER DYNAMIC TABLE CURATED.FINDING_TRACKER REFRESH;
ALTER DYNAMIC TABLE CURATED.COMPLIANCE_CALENDAR REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM REGULATORY_REPORTING.RAW.FINANCIAL_DATA → 8500000
-- SELECT COUNT(*) FROM REGULATORY_REPORTING.RAW.BSP_CIRCULARS → 450
-- SELECT COUNT(*) FROM REGULATORY_REPORTING.CURATED.REPORT_READINESS WHERE READINESS_SCORE < 80 → >=12

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_RECONCILE RESUME;
ALTER TASK IF EXISTS APP.TASK_GENERATE_REPORTS RESUME;
ALTER TASK IF EXISTS APP.TASK_VALIDATE_DATA RESUME;
ALTER TASK IF EXISTS APP.TASK_EXTRACT_GL RESUME;
